# Generated by Django 5.0.4 on 2025-04-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='File Number')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Patient Name')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('OT', 'OT'), ('ST', 'ST'), ('SE', 'SE'), ('BEH', 'BEH'), ('PT', 'PT')], max_length=4, verbose_name='Service Type')),
                ('insurance', models.CharField(choices=[('Thiqa', 'Thiqa'), ('Enhanced', 'Enhanced'), ('Cash', 'Cash'), ('Free', 'Free')], max_length=10, verbose_name='Insurance')),
                ('num_of_session', models.PositiveIntegerField(default=10, verbose_name='Total Sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='employees.file')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('is_session', models.BooleanField(default=True, verbose_name='Session (True=session, False=follow-up)')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Patient Name')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of Communication')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_records', to='employees.paymenttype')),
            ],
        ),
    ]
